version: "3.8"
services:

  client:
    container_name: client
    build: 
      context: client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./client:/front
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - server
    networks:
      - mern-network

  server:
    container_name: server
    build:  
      context: server
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - ./server:/usr/src/api
    depends_on:
      - mongo
    restart: always
    networks:
      - mern-network

  mongo:
    hostname: mongo
    container_name: mongo
    image: mongo:latest
    ports:
      - '27018:27017'
    volumes:
      - /home/theo/mongo-backup:/data/db
    networks:
      - mern-network


networks:
  mern-network:
    driver: bridge